spring:
  # h2 DB 설정
  #Jasypt암호화
  datasource:
    url: ENC(JR7de8kI38KKyX/3YQY6a/0Se0ZMcjyg8D+mQF1tLCb6TR8AJmNYF27z6sm2hvLZBgrrQjO7MYgjhypygeM+xfSTeP+lQZ2TT8BNH4dKISkAEpbW8UMdeA==)
    username: ENC(YNzp2RJUoKmYSAATgWrH9w==)
    password: ENC(mR+TghZnvrX8aj5KyWJ5FU5wMAo/K4gs)
    driver-class-name: org.mariadb.jdbc.Driver
  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  # devtools 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    mode: HTML5
    cache: false
    prefix: file:src/main/resources/templates/

  main:
    allow-bean-definition-overriding: true
# sql스크립트 인입시
  sql:
    init:
      schema-locations: classpath:db/data.sql
      mode: always
      encoding: utf-8

logging.level:
  org.hibernate.SQL: debug